### PR TITLE
stepped_knob snaps to valid values, removed max/min

### PR DESCRIPTION
**Pull request by Fredemus**
Having knobs not know too much about the parameters makes them simpler and avoids glitches when parameters have nonlinear set functions, i.e. when you want a parameter to be set with a different slope. For example, the drive parameter in this filter plugin is set with x^2 to make the knob feel more natural to use (moves slowly through values at the start, then faster) [link](https://github.com/Fredemus/svf_filter/blob/main/src/filter_parameters.rs#L83-L91).
Instead of `parameter.set(*knob.p_value)`, i do `self.params.set_parameter(parameter_index, *knob.p_value)`
and have the knobs always be in the range [0, 1]. You can see how this looks at [here](https://github.com/Fredemus/svf_filter/blob/main/src/editor.rs#L151-L162)
This also makes it simpler to call `automate(parameter_index, *knob.p_value)`
on the HostCallback, which notifies the host when and how parameters change.

Also I made the stepped knob snap to the steps, which feels more natural imo.

### CODE REVIEW

**Comment by DGriffin91** [comment]
@Fredemus Thanks for submitting this! I think this design overall makes more sense. I wonder if it would make sense to have a `knob_with_drag_range` in addition to the `knob_with_drag` where the ranged version would be a bit more like before, to make it easy to have linear knobs with the min/max? `knob_with_drag` in a lot of ways is really just an example of how to use the knob, so maybe a `knob_with_drag_range` would be an useful additional reference? I'm not asking you to implement this, more just thinking out loud, and also curious if you have any insight.

In imgui style, I would like the knobs in some way or another to be used with minimal boilerplate. 

We also need to update the demo and examples to work with these changes.

**Comment by Fredemus** [comment]
No problem! Your trailblazing with imgui vsts saved me a ton of time! 

For the sake of vsts at least you can still easily do linear parameters in a certain range. I used [your parameter struct from your compressor as a basis](https://github.com/DGriffin91/compressor-plugin/blob/main/src/parameter.rs)

Then in the `set_parameter` function I just call the `set_normalized` function which takes values in the range [0,1] and transforms it with the parameter's min and max:
[set_parameter](https://github.com/Fredemus/svf_filter/blob/main/src/lib.rs#L380-L391)
And then just call the `set_parameter` function when the knob value changes as mentioned in my first post.

Though I can see how it might be nice to have range built into the knobs for other purposes than a vst. Maybe there should be both a `Knob_range`and a `Knob_no_range` struct? For my purposes at least I'd prefer if my knobs weren't doing unnecessary multiplication/additions.

Didn't even think of the examples, I'll make sure to update them when I have some spare time. It seems like they need to use a knob struct with `v_max` and `v_min` fields, which is why I think 2 knob structs might be the best solution, but it's up to you :) I can just use my own fork if you'd rather just have 1 with `v_max` and `v_min`.

On another note, something weird happens with knob placements when I run the example on my machine (not only on my fork). [picture](https://imgur.com/fvryPHz). I can open an issue for this if you want

**Comment by DGriffin91** [comment]
@Fredemus I'm really glad the work I started was helpful!!

I like the idea of having a basic linear knob available for simple use cases. And I also think having the struct be just normalized to 0-1 (like what you have) makes more sense. I'm not sure we actually need a seperate struct for the ranged vs non ranged version. Couldn't we just do it in the  `knob_with_drag`  function?

Using the word range gets a bit weird in the context of the Dear ImGui library as `DragFloatRange` is a different kind of thing where the min and max are variable. But I'm not sure if that really matters, as this library already breaks some Dear ImGui conventions. (like with the color input)

Go ahead and leave an issue regarding the demo.

**Comment by Fredemus** [comment]
Sorry, I've been busy and didn't have time to look at this before now 

I've been looking into making a `knob_with_drag_range` function (which behaves the same way as `knob_with_drag` without my changes). Just doing it the simple way and not having a min and max on the knob didn't work.

I think the problem is in this part of the `knob_with_drag` function:

```rust
let knob = Knob::new(ui, id, p_value, v_default, width * 0.5, true);

    Drag::new(&ImString::new(format!(
        "###{}_KNOB_DRAG_CONTORL_",
        id.to_str()
    )))
    .range(v_min..=v_max)
    .display_format(format)
    .speed((v_max - v_min) / 1000.0)
    .build(ui, knob.p_value);
```
The `Drag`  object seems to be adjustable and work as expected when you click the text under the knob and drag horizontally. This changes `knob.p_value` between the range, as you'd expect, though the knob tick moves weirdly.

However when you click the actual knob you have to drag it vertically and it sets `knob.p_value` in the range [0,1]. This is done by the `knob_control` function and I don't think the `Drag` object is doing anything here.

So it seems like this function creates 2 conflicting ways of interacting with the knob. I'm not sure about the right way to fix this. Maybe a `knob_control_range` function? Or somehow avoid `knob_control` and use a `Drag` object instead? Though I'm not sure how to change it to be vertical instead

**Comment by DGriffin91** [comment]
@Fredemus Sorry I didn't give this much attention. I haven't been using this library at all since your first pull request. Thanks for the discussion though, it will be helpful in the future :)

**Pull request closed without merging**
